### ISSUE TITLE
Unexpected Error during Training: AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by Swall0w** [ZeningLin/PEneo#2]
Thank you very much for your excellent research and code publication.
To reproduce it, I followed the procedure described in the [README](https://github.com/ZeningLin/PEneo?tab=readme-ov-file#pair-extraction-on-rfund), and when I ran it, an error occurred.
Have you experienced any similar errors?

```bash
[INFO|modeling_utils.py:4170] 2024-08-23 09:37:22,095 >> All model checkpoint weights were used when initializing PEneoModel.

[WARNING|modeling_utils.py:4172] 2024-08-23 09:37:22,095 >> Some weights of PEneoModel were not initialized from the model checkpoint at private_pretrained/layoutlmv3-base and are newly initialized...
[INFO|trainer.py:2048] 2024-08-23 09:37:23,332 >> ***** Running training *****
[INFO|trainer.py:2057] 2024-08-23 09:37:23,333 >>   Number of trainable parameters = 127,252,750
  0%|          | 0/25000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/accelerate/utils/operations.py", line 155, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/works/PEneo/start/run_rfund.py", line 336, in <module>
    main()
  File "/home/jack/works/PEneo/start/run_rfund.py", line 319, in main
    train_result = trainer.train(
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/trainer.py", line 2165, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/accelerate/data_loader.py", line 463, in __iter__
    current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/accelerate/utils/operations.py", line 157, in send_to_device
    return tensor.to(device)
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 800, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 800, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
AttributeError: 'list' object has no attribute 'to'

```
## Environment
- Python version: 3.10
- Transformers version: 4.40.1
- PyTorch version: 2.0.1+cu117

## Steps to Reproduce
- Clone the repository.
- Follow the provided setup instructions.
- Run the training script as specified.

**Comment by ZeningLin** [comment]
It seems that the error is raised by the `accelerate` engine when moving the data to the target device, while this operation should be handled by the `DataCollatorForPEneo` in `data/collator.py`, not the `accelerate` engine. Could you please show me your shell script for starting the training task?

**Comment by Swall0w** [comment]
@ZeningLin Thank you for your quick response. I followed the shell scripts in the README, so it is the following.
```bash
export PYTHONPATH=./
export CUDA_VISIBLE_DEVICES=0,1
export TRANSFORMERS_NO_ADVISORY_WARNINGS='true'
PROC_PER_NODE=$(python -c "import torch; print(torch.cuda.device_count())")
MASTER_PORT=11451

LANGUAGE=en
TASK_NAME=layoutlmv3-base_rfund_${LANGUAGE}
PRETRAINED_PATH=private_pretrained/layoutlmv3-base
DATA_DIR=private_data/rfund
OUTPUT_DIR=private_output/weights/$TASK_NAME
RUNS_DIR=private_output/runs/$TASK_NAME
LOG_DIR=private_output/logs/$TASK_NAME.log
torchrun --nproc_per_node $PROC_PER_NODE --master_port $MASTER_PORT start/run_rfund.py \
         --model_name_or_path $PRETRAINED_PATH \
         --data_dir $DATA_DIR \
         --language $LANGUAGE \
         --output_dir $OUTPUT_DIR \
         --do_train \
         --do_eval \
         --fp16 \
         --per_device_train_batch_size 4 \
         --per_device_eval_batch_size 16 \
         --dataloader_num_workers 8 \
         --warmup_ratio 0.1 \
         --learning_rate 5e-5 \
         --max_steps 25000 \
         --evaluation_strategy steps \
         --eval_steps 1000 \
         --save_strategy steps \
         --save_steps 1000 \
         --save_total_limit 1 \
         --logging_strategy epoch \
         --logging_dir $RUNS_DIR \
         --detail_eval True \
         --save_eval_detail True \
         2>&1 | tee -a $LOG_DIR
```

I reinstalled the transformers with the specified versions **4.40.0** and **4.37.1**, but the error remained the same.
After that, I also uninstalled Accelerate just in case, but another error showed that Accelerate is needed for Trainer.

```bash
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/jack/works/PEneo/start/run_rfund.py", line 336, in <module>
    main()
  File "/home/jack/works/PEneo/start/run_rfund.py", line 117, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/jack/works/PEneo/start/run_rfund.py", line 336, in <module>
    main()
  File "/home/jack/works/PEneo/start/run_rfund.py", line 117, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 121, in __init__
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/training_args.py", line 1483, in __post_init__
    and (self.device.type != "cuda")
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/training_args.py", line 1921, in device
    return self._setup_devices
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/jack/anaconda3/envs/vie/lib/python3.10/site-packages/transformers/training_args.py", line 1831, in _setup_devices
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.21.0`: Please run `pip install transformers[torch]` or `pip install accelerate -U`
````

**Comment by ZeningLin** [comment]
It seems weird 😦 since I've never met an issue like this in the past. I will try to reproduce the error and find a solution these days.

**Comment by isXuedingesCat** [comment]
try install accelerate==0.27.2  it`s work for me。with system win10, Environment same like you.

**Comment by ZeningLin** [comment]
> try install accelerate==0.27.2 it`s work for me with system win10, Environment same like you.

@Swall0w Can this solution fix the issue on your device?

**Comment by Swall0w** [comment]
@ZeningLin @isXuedingesCat Thank you so much:) 
This solution also works for me. I checked the presented rfund training was completed.

> try install accelerate==0.27.2 it`s work for me。with system win10, Environment same like you.
