### ISSUE TITLE
ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.

### ISSUE THREAD

**Issue by 67aaa** [ZeningLin/PEneo#7]
Hello, When I run your code, there is a mistake happened.Can you tell me how to solve it? thank you
I try to use this command, but the same mistakes persist
batch["image"] = self.image_processor(images, return_tensors="pt",padding=True)[
                "pixel_values"
            ]

Traceback (most recent call last):
  File “envs/vie/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "envs/vie/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "PEneo/data/collator.py", line 226, in __call__
    batch["image"] = self.image_processor(
  File "/envs/vie/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 551, in __call__
    return self.preprocess(images, **kwargs)
  File "/envs/vie/lib/python3.10/site-packages/transformers/models/layoutlmv3/image_processing_layoutlmv3.py", line 382, in preprocess
    data = BatchFeature(data={"pixel_values": images}, tensor_type=return_tensors)
  File "envs/vie/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 78, in __init__
    self.convert_to_tensors(tensor_type=tensor_type)
  File "envs/vie/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 188, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.

  0%|          | 0/25000 [00:13<?, ?it/s]

**Comment by ZeningLin** [comment]
Sorry for my late reply.

Could you please tell me the version of the `transformers` package in your environment?

**Comment by ZeningLin** [comment]
It seems that the images within the same batch are in different shapes. The error may occur when the image resize operation in the preprocessor is not properly performed. You may check the `do_size` field in the `preprocessor_config.json` in your pre-trained layoutlmv3 backbone directory and make sure that it is set to `true`.

**Comment by 67aaa** [comment]
> It seems that the images within the same batch are in different shapes. The error may occur when the image resize operation in the preprocessor is not properly performed. You may check the `do_size` field in the `preprocessor_config.json` in your pre-trained layoutlmv3 backbone directory and make sure that it is set to `true`.

I just confirmed that do_resize is true, and the version of transformers is the same as that in requirements.txt, which is 4.40.1, but the same error is still reported.

**Comment by ZeningLin** [comment]
Thanks for your feedback. Looks like something is wrong with your image data.

In `/envs/vie/lib/python3.10/site-packages/transformers/models/layoutlmv3/image_processing_layoutlmv3.py`, line 382, before constructing the `BatchFeature` object, all of the images should be resized to `(3, 224, 224)`. Could you check the shape of these images in debugging mode?

**Comment by 67aaa** [comment]
Thank you for your answer. I have just reduced the numpy version to 1.21, and now we can start training. I would like to ask where the pair extraction results are saved after training？

**Comment by ZeningLin** [comment]
To get the pair extraction results after training, you should set the `--detail_eval` and `--save_eval_detail` flags to `True` in the training script. Results will be saved to `detail.json` file in the `$OUTPUT_DIR`, which is set to `private_output/weights/$TASK_NAME` by default.

**Comment by 67aaa** [comment]
OK, I see.Thank you so much!
